Repository headF1rst/promisor, pull requests merged in 2022-04, with the labels that each got.

#68 Fix: Modify login API jwt Logic
  src/main/java/promisor/promisor/domain/auth/AuthenticationInterceptor.java
  src/main/java/promisor/promisor/domain/auth/EnableAuth.java
  src/main/java/promisor/promisor/domain/member/api/MemberController.java
  src/main/java/promisor/promisor/domain/member/api/RelationController.java
  src/main/java/promisor/promisor/domain/member/dao/RefreshTokenRepository.java
  src/main/java/promisor/promisor/domain/member/dao/RelationRepository.java
  src/main/java/promisor/promisor/domain/member/domain/RefreshToken.java
  src/main/java/promisor/promisor/domain/member/dto/LoginDto.java
  src/main/java/promisor/promisor/domain/member/dto/LoginResponse.java
  src/main/java/promisor/promisor/domain/member/exception/ForbiddenUserException.java
  src/main/java/promisor/promisor/domain/member/exception/LoginAgainException.java
  src/main/java/promisor/promisor/domain/member/service/CustomUserDetailService.java
  src/main/java/promisor/promisor/domain/member/service/MemberService.java
  src/main/java/promisor/promisor/global/config/ApiResponse.java
  src/main/java/promisor/promisor/global/config/ResponseMap.java
  src/main/java/promisor/promisor/global/config/WebSecurityConfig.java
  src/main/java/promisor/promisor/global/config/security/JwtProvider.java
  src/main/java/promisor/promisor/global/error/ErrorCode.java
Labels: 개발 🧑‍💻, 리팩터링 🔧, 우선순위 ⭐⭐⭐

#71 Feature: feat updateGroupName API
  src/main/java/promisor/promisor/domain/member/dao/RelationRepository.java
  src/main/java/promisor/promisor/domain/team/api/TeamController.java
  src/main/java/promisor/promisor/domain/team/dao/TeamRepository.java
  src/main/java/promisor/promisor/domain/team/domain/Team.java
  src/main/java/promisor/promisor/domain/team/dto/EditGroupDto.java
  src/main/java/promisor/promisor/domain/team/exception/GroupIdNotFound.java
  src/main/java/promisor/promisor/domain/team/service/TeamService.java
  src/main/java/promisor/promisor/global/error/ErrorCode.java
Labels: 개발 🧑‍💻, 백 🐯, 우선순위 ⭐⭐

#73 Feature: Add jwt Annotaion OAuth logic
  src/main/java/promisor/promisor/domain/member/api/RelationController.java
  src/main/java/promisor/promisor/domain/member/dao/MemberRepository.java
  src/main/java/promisor/promisor/domain/member/dto/FollowFriendRequest.java
  src/main/java/promisor/promisor/domain/member/service/MemberService.java
  src/main/java/promisor/promisor/global/auth/AuthorizationExtractor.java
  src/main/java/promisor/promisor/global/auth/JwtAuth.java
  src/main/java/promisor/promisor/global/auth/JwtAuthArgumentResolver.java
  src/main/java/promisor/promisor/global/auth/ProfileTokenResponse.java
  src/main/java/promisor/promisor/global/auth/jwtService.java
  src/main/java/promisor/promisor/global/config/WebConfig.java
  src/main/java/promisor/promisor/global/config/WebSecurityConfig.java
  src/main/java/promisor/promisor/global/config/security/JwtProvider.java
  src/main/java/promisor/promisor/global/config/security/jwtAuthenticationFilter.java
  src/main/java/promisor/promisor/global/secret/SecretConfig.java
  src/main/java/promisor/promisor/global/secret/SecretKey.java
  src/main/java/promisor/promisor/infra/email/JwtTokenProvider.java
  src/main/resources/application.yml
  src/test/java/promisor/promisor/domain/member/service/MemberServiceTest.java
Labels: 개발 🧑‍💻, 리팩터링 🔧, 우선순위 ⭐⭐⭐, 백 🐯

#78 Fix: 친구 요청, 조회 API 형식 수정
  src/main/java/promisor/promisor/domain/member/api/RelationController.java
  src/main/java/promisor/promisor/domain/member/domain/Member.java
  src/main/java/promisor/promisor/domain/member/domain/Relation.java
  src/main/java/promisor/promisor/domain/member/dto/MemberResponse.java
  src/main/java/promisor/promisor/domain/member/service/MemberService.java
  src/main/java/promisor/promisor/domain/member/service/RelationService.java
  src/main/java/promisor/promisor/domain/team/domain/Team.java
  src/main/java/promisor/promisor/domain/team/service/TeamService.java
  src/main/java/promisor/promisor/global/config/WebSecurityConfig.java
  src/main/java/promisor/promisor/global/config/security/JwtAuthenticationFilter.java
  src/main/java/promisor/promisor/global/config/security/JwtProvider.java
  src/main/java/promisor/promisor/global/config/security/jwtAuthenticationFilter.java
  src/main/java/promisor/promisor/global/error/CustomAuthenticationEntryPoint.java
  src/main/java/promisor/promisor/global/error/ErrorCode.java
  src/main/java/promisor/promisor/global/error/WebAccessDeniedHandler.java
  src/main/java/promisor/promisor/global/error/exception/ApplicationException.java
  src/main/java/promisor/promisor/global/token/ConfirmationTokenDAO.java
Labels: 개발 🧑‍💻, 백 🐯, 우선순위 ⭐⭐

#80 Feat: Feature 친구 삭제 API(#79)
  src/main/java/promisor/promisor/domain/member/api/RelationController.java
  src/main/java/promisor/promisor/domain/member/domain/Member.java
  src/main/java/promisor/promisor/domain/member/service/MemberService.java
  src/main/java/promisor/promisor/domain/member/service/RelationService.java
  src/main/java/promisor/promisor/global/error/exception/ApplicationException.java
Labels: 개발 🧑‍💻, 백 🐯, 우선순위 ⭐⭐

#83 Feat: Feature 사용자 친구 전체조회 API (#81)
  src/main/java/promisor/promisor/domain/member/api/RelationController.java
  src/main/java/promisor/promisor/domain/member/domain/Member.java
  src/main/java/promisor/promisor/domain/member/service/RelationService.java
Labels: 개발 🧑‍💻, 백 🐯, 우선순위 ⭐⭐

#86 Fix: fix refreshTokenId is null error
  src/main/java/promisor/promisor/domain/member/dto/LoginResponse.java
  src/main/java/promisor/promisor/domain/member/dto/TokenResponse.java
  src/main/java/promisor/promisor/domain/member/service/MemberService.java
  src/main/java/promisor/promisor/global/config/security/JwtProvider.java
  src/main/resources/application.yml
Labels: 버그 🪲, 백 🐯, 우선순위 ⭐⭐

#87 Feat: Add JwtExceptionFilter
  src/main/java/promisor/promisor/global/auth/JwtExceptionFilter.java
  src/main/java/promisor/promisor/global/config/WebSecurityConfig.java
  src/main/java/promisor/promisor/global/error/CustomAuthenticationEntryPoint.java
  src/main/java/promisor/promisor/global/token/JwtExceptionResponse.java
Labels: 버그 🪲, 백 🐯, 우선순위 ⭐⭐

#90 Feat: Add jwtExceptionFilter for handling token exception (#89)
  src/main/java/promisor/promisor/domain/member/dto/LoginDto.java
  src/main/java/promisor/promisor/domain/member/dto/SignUpDto.java
  src/main/java/promisor/promisor/global/auth/JwtExceptionFilter.java
  src/main/java/promisor/promisor/global/config/WebSecurityConfig.java
  src/main/java/promisor/promisor/global/config/security/JwtAuthenticationFilter.java
  src/main/java/promisor/promisor/global/config/security/JwtProvider.java
Labels: 개발 🧑‍💻, 우선순위 ⭐⭐⭐, 백 🐯

#96 Fix: Refactor team entity name to group (#95)
  build.gradle
  src/main/java/promisor/promisor/domain/chat/Chat.java
  src/main/java/promisor/promisor/domain/goal/Goal.java
  src/main/java/promisor/promisor/domain/group/api/GroupController.java
  src/main/java/promisor/promisor/domain/group/dao/GroupRepository.java
  src/main/java/promisor/promisor/domain/group/domain/Group.java
  src/main/java/promisor/promisor/domain/group/domain/Invite.java
  src/main/java/promisor/promisor/domain/group/domain/TeamMember.java
  src/main/java/promisor/promisor/domain/group/dto/CreateGroupDto.java
  src/main/java/promisor/promisor/domain/group/dto/EditGroupDto.java
  src/main/java/promisor/promisor/domain/group/exception/GroupIdNotFound.java
  src/main/java/promisor/promisor/domain/group/service/GroupService.java
  src/main/java/promisor/promisor/domain/member/api/MemberController.java
  src/main/java/promisor/promisor/domain/member/api/RelationController.java
  src/main/java/promisor/promisor/domain/member/dao/MemberRepository.java
  src/main/java/promisor/promisor/domain/member/dto/LoginDto.java
  src/main/java/promisor/promisor/domain/promise/api/PromiseController.java
  src/main/java/promisor/promisor/domain/promise/domain/Promise.java
  src/main/java/promisor/promisor/domain/team/dao/TeamRepository.java
  src/main/java/promisor/promisor/domain/team/service/TeamService.java
  src/main/java/promisor/promisor/global/config/SwaggerConfig.java
  src/main/java/promisor/promisor/global/error/ApplicationExceptionHandler.java
Labels: 리팩터링 🔧, 백 🐯, 우선순위 ⭐⭐

#98 Add/friend profile search
  client/package.json
  client/src/atoms/FriendProfileSearch.tsx
  client/src/atoms/ThinBar.tsx
  client/src/organisms/AddModal.tsx
  client/src/organisms/FriendAdd.tsx
  client/src/pages/Group.tsx
Labels: 개발 🧑‍💻, 리팩터링 🔧, 프론트 🐰

#99 Update: README.md
  README.md
Labels: 확인 🔪

#108 Feat: Add promise creation API (#103)
  src/main/java/promisor/promisor/domain/member/dao/MemberRepository.java
  src/main/java/promisor/promisor/domain/member/domain/Member.java
  src/main/java/promisor/promisor/domain/member/domain/MemberRole.java
  src/main/java/promisor/promisor/domain/promise/api/PromiseController.java
  src/main/java/promisor/promisor/domain/promise/dao/PromiseRepository.java
  src/main/java/promisor/promisor/domain/promise/domain/Promise.java
  src/main/java/promisor/promisor/domain/promise/service/PromiseService.java
  src/main/java/promisor/promisor/domain/team/dao/TeamRepository.java
  src/main/java/promisor/promisor/domain/team/domain/Team.java
  src/main/java/promisor/promisor/domain/team/exception/TeamNotFoundForMember.java
  src/main/java/promisor/promisor/global/error/ErrorCode.java
Labels: 개발 🧑‍💻, 우선순위 ⭐⭐⭐, 백 🐯

#114 Fix: Fix promise creation API input spec(#103)
  src/main/java/promisor/promisor/domain/promise/api/PromiseController.java
  src/main/java/promisor/promisor/domain/promise/dto/PromiseCreateRequest.java
  src/main/java/promisor/promisor/domain/promise/service/PromiseService.java
  src/main/java/promisor/promisor/domain/team/dao/TeamMemberRepository.java
  src/main/java/promisor/promisor/domain/team/domain/Team.java
  src/main/java/promisor/promisor/domain/team/domain/TeamMember.java
  src/main/java/promisor/promisor/domain/team/dto/CreateTeamDto.java
  src/main/java/promisor/promisor/domain/team/service/TeamService.java
Labels: 개발 🧑‍💻, 리팩터링 🔧, 우선순위 ⭐⭐

#120 Add/my page
  client/src/App.tsx
  client/src/organisms/MyPageModal.tsx
  client/src/organisms/SideMenu.tsx
  client/src/pages/Home.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/Setting.tsx
  client/src/pages/_index.ts
Labels: 개발 🧑‍💻, 프론트 🐰

#124 Feat: Add searchPromiseByGroup API(#121)
  src/main/java/promisor/promisor/domain/member/api/MemberController.java
  src/main/java/promisor/promisor/domain/member/api/RelationController.java
  src/main/java/promisor/promisor/domain/member/dto/ModifyMemberDto.java
  src/main/java/promisor/promisor/domain/member/service/MemberService.java
  src/main/java/promisor/promisor/domain/place/domain/Place.java
  src/main/java/promisor/promisor/domain/promise/api/PromiseController.java
  src/main/java/promisor/promisor/domain/promise/dao/PromiseRepository.java
  src/main/java/promisor/promisor/domain/promise/domain/Promise.java
  src/main/java/promisor/promisor/domain/promise/dto/PromiseResponse.java
  src/main/java/promisor/promisor/domain/promise/exception/MemberNotBelongsToTeam.java
  src/main/java/promisor/promisor/domain/promise/service/PromiseService.java
  src/main/java/promisor/promisor/domain/team/dao/TeamMemberRepository.java
  src/main/java/promisor/promisor/global/error/ErrorCode.java
Labels: 개발 🧑‍💻, 백 🐯, 우선순위 ⭐⭐

#129 Fix: Modify promiseCreation API, No role provide(#128)
  src/main/java/promisor/promisor/domain/promise/service/PromiseService.java
Labels: 리팩터링 🔧, 우선순위 ⭐, 백 🐯
