Repository headF1rst/promisor, pull requests merged in 2022-05, with the labels that each got.

#136 Feat/add date recommendation
  client/package.json
  client/src/Theme.ts
  client/src/organisms/PromiseDateCalendar.tsx
  client/src/organisms/PromiseDateRecommendation.tsx
  client/src/organisms/RoundList.tsx
  client/src/organisms/SideMenu.tsx
  client/src/pages/Group.tsx
  client/src/pages/Home.tsx
  client/src/pages/PromiseDate.tsx
  client/yarn.lock
  yarn.lock
Labels: 개발 🧑‍💻, 프론트 🐰

#142 Feat: Delete date recommend list (#141)
  client/src/organisms/PromiseDateRecommendation.tsx
  client/src/pages/PromiseDate.tsx
Labels: 설계 📐, 개발 🧑‍💻, 프론트 🐰

#145 Refactor: Add rateLimiting to group creation API(#144)
  src/main/java/promisor/promisor/domain/team/exception/TooManyRequestException.java
Labels: 개발 🧑‍💻, 리팩터링 🔧, 백 🐯

#152 Feat: Add GroupSearch API (#135)
  build.gradle
  src/main/java/promisor/promisor/domain/team/api/TeamController.java
  src/main/java/promisor/promisor/domain/team/dao/TeamRepository.java
  src/main/java/promisor/promisor/domain/team/dto/GroupMemberDto.java
  src/main/java/promisor/promisor/domain/team/dto/SearchGroupResponse.java
  src/main/java/promisor/promisor/domain/team/exception/TooManyRequestException.java
  src/main/java/promisor/promisor/domain/team/service/TeamService.java
  src/main/java/promisor/promisor/global/error/ErrorCode.java
Labels: 개발 🧑‍💻, 백 🐯, 우선순위 ⭐⭐

#147 Feat: Add domain Bandate
  src/main/java/promisor/promisor/domain/BanDate/PersonalBanDate.java
  src/main/java/promisor/promisor/domain/BanDate/TeamBanDate.java
  src/main/java/promisor/promisor/domain/promise/domain/BanDate.java
  src/main/java/promisor/promisor/global/config/OpenApiConfig.java
Labels: 개발 🧑‍💻, 리팩터링 🔧, 백 🐯, 우선순위 ⭐⭐

#154 Feat/link create group api
  client/src/organisms/AddModal.tsx
  client/src/organisms/GroupMakerSelectedList.tsx
  client/src/pages/Group.tsx
  client/src/pages/GroupMaker.tsx
Labels: 개발 🧑‍💻, 프론트 🐰

#157 Fix: Fix rate limiting, createGroup return id
  src/main/java/promisor/promisor/domain/team/api/TeamController.java
  src/main/java/promisor/promisor/domain/team/service/TeamService.java
  src/main/java/promisor/promisor/global/error/ErrorCode.java
Labels: 버그 🪲, 개발 🧑‍💻, 리팩터링 🔧, 백 🐯, 우선순위 ⭐⭐

#162 Feat: Fix rendering Friends list immediately (#161)
  client/src/atoms/Profile.tsx
  client/src/auth/config.ts
  client/src/image/user.png
  client/src/index.tsx
  client/src/organisms/FriendAdd.tsx
  client/src/pages/Friend.tsx
  client/src/pages/Group.tsx
Labels: 개발 🧑‍💻, 프론트 🐰

#170 Feat/link load profile api
  client/src/App.tsx
  client/src/pages/Group.tsx
  client/src/pages/Home.tsx
  client/src/pages/MyPage.tsx
Labels: 개발 🧑‍💻, 프론트 🐰

#166 Fix: Add JWT empty exception(#159)
  src/main/java/promisor/promisor/domain/bandate/PersonalBanDate.java
  src/main/java/promisor/promisor/domain/bandate/TeamBanDate.java
  src/main/java/promisor/promisor/global/config/security/JwtAuthenticationFilter.java
Labels: 버그 🪲, 개발 🧑‍💻, 우선순위 ⭐

#171 Fix: Fix GroupSearch API Logic (#168)
  src/main/java/promisor/promisor/domain/team/api/TeamController.java
  src/main/java/promisor/promisor/domain/team/dao/TeamRepository.java
  src/main/java/promisor/promisor/domain/team/service/TeamService.java
  src/main/java/promisor/promisor/global/config/security/JwtAuthenticationFilter.java
Labels: 버그 🪲, 개발 🧑‍💻, 백 🐯

#183 Fix: Fix CORS (#181)
  src/main/java/promisor/promisor/global/config/WebConfig.java
Labels: 버그 🪲, 개발 🧑‍💻, 우선순위 ⭐⭐⭐, 백 🐯

#182 Refactor: Login API return jwt expireTime (#172)
  Jenkinsfile.promisor
  src/main/java/promisor/promisor/domain/bandate/domain/PersonalBanDate.java
  src/main/java/promisor/promisor/domain/bandate/domain/TeamBanDate.java
  src/main/java/promisor/promisor/domain/member/api/MemberController.java
  src/main/java/promisor/promisor/domain/member/dto/LoginResponse.java
  src/main/java/promisor/promisor/domain/member/service/MemberService.java
  src/main/java/promisor/promisor/domain/model/BaseEntity.java
  src/main/java/promisor/promisor/domain/team/domain/Invite.java
  src/main/java/promisor/promisor/domain/team/domain/Team.java
  src/main/java/promisor/promisor/global/config/security/JwtProvider.java
  src/main/resources/application.yml
Labels: 리팩터링 🔧, 백 🐯, 우선순위 ⭐⭐

#204 Feat: GetTeamMembersLocation (#203)
  build.gradle
  src/main/java/promisor/promisor/domain/team/api/TeamController.java
  src/main/java/promisor/promisor/domain/team/dto/GetTeamMembersLocationResponse.java
  src/main/java/promisor/promisor/domain/team/service/TeamService.java
Labels: 개발 🧑‍💻, 우선순위 ⭐⭐⭐, 백 🐯

#206 Feat: Add Promise Location (#197)
  client/package.json
  client/public/index.html
  client/src/App.tsx
  client/src/atoms/Checkbox.tsx
  client/src/image/marker.png
  client/src/organisms/PlaceList.tsx
  client/src/organisms/PromiseLocaionMap.tsx
  client/src/pages/Login.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/PromiseDetail.tsx
  client/src/pages/PromiseLocation.tsx
  client/src/utils/kakaoMap.ts
  client/tsconfig.json
  client/yarn.lock
Labels: 개발 🧑‍💻, 프론트 🐰

#207 Refactor: Modify login return tokenExpireDate (#200)
  src/main/java/promisor/promisor/domain/member/service/MemberService.java
  src/main/java/promisor/promisor/global/config/security/JwtProvider.java
Labels: 개발 🧑‍💻, 리팩터링 🔧, 우선순위 ⭐⭐

#209 Fix: Fix group search NPE (#208)
  src/main/java/promisor/promisor/domain/promise/domain/Promise.java
Labels: 버그 🪲, 개발 🧑‍💻, 백 🐯, 우선순위 ⭐⭐

#220 Add: Add origins for cors
  src/main/java/promisor/promisor/domain/chat/Chat.java
  src/main/java/promisor/promisor/domain/goal/Goal.java
  src/main/java/promisor/promisor/domain/manager/Manager.java
  src/main/java/promisor/promisor/domain/member/service/RelationService.java
  src/main/java/promisor/promisor/global/config/WebConfig.java
  src/main/java/promisor/promisor/global/token/ConfirmationTokenRepository.java
  src/main/java/promisor/promisor/global/token/ConfirmationTokenService.java
Labels: 개발 🧑‍💻, 리팩터링 🔧, 백 🐯

#224 Feat: Modify editPersonalBandateAPI(#222)
  src/main/java/promisor/promisor/domain/bandate/api/BanDateController.java
  src/main/java/promisor/promisor/domain/bandate/dto/ModifyStatusDto.java
  src/main/java/promisor/promisor/domain/bandate/dto/ModifyStatusResponse.java
  src/main/java/promisor/promisor/domain/bandate/dto/PersonalBanDateStatusEditRequest.java
  src/main/java/promisor/promisor/domain/bandate/service/BanDateService.java
Labels: 개발 🧑‍💻

#234 Fix: State rendering error
  client/src/organisms/PromiseDateCalendar.tsx
  client/src/organisms/PromiseLocationMap.tsx
  client/src/pages/PromiseDate.tsx
  client/src/pages/PromiseDetail.tsx
  client/src/pages/PromiseLocation.tsx
Labels: 버그 🪲, 프론트 🐰
