Repository headF1rst/promisor, pull requests merged in 2022-06, with the labels that each got.

#248 Feat: Feat update promise API (#223)
  src/main/java/promisor/promisor/domain/bandate/dao/PersonalBanDateRepository.java
  src/main/java/promisor/promisor/domain/bandate/domain/PersonalBanDate.java
  src/main/java/promisor/promisor/domain/bandate/domain/PersonalBanDateReason.java
  src/main/java/promisor/promisor/domain/member/domain/Member.java
  src/main/java/promisor/promisor/domain/place/domain/Place.java
  src/main/java/promisor/promisor/domain/place/domain/PlaceImage.java
  src/main/java/promisor/promisor/domain/promise/api/PromiseController.java
  src/main/java/promisor/promisor/domain/promise/dao/PromiseRepository.java
  src/main/java/promisor/promisor/domain/promise/domain/Opinion.java
  src/main/java/promisor/promisor/domain/promise/domain/Promise.java
  src/main/java/promisor/promisor/domain/promise/service/PromiseService.java
  src/main/java/promisor/promisor/domain/store/domain/Store.java
  src/main/java/promisor/promisor/domain/team/domain/Team.java
  src/main/java/promisor/promisor/domain/team/domain/TeamMember.java
Labels: 개발 🧑‍💻, 리팩터링 🔧, 우선순위 ⭐⭐⭐, 백 🐯

#252 Feat: Add promise search API (#249)
  src/main/java/promisor/promisor/domain/bandate/domain/TeamBanDate.java
  src/main/java/promisor/promisor/domain/place/domain/Place.java
  src/main/java/promisor/promisor/domain/promise/api/PromiseController.java
  src/main/java/promisor/promisor/domain/promise/dao/PromiseRepository.java
  src/main/java/promisor/promisor/domain/promise/dto/PromiseResponse.java
  src/main/java/promisor/promisor/domain/promise/service/PromiseService.java
  src/main/java/promisor/promisor/global/config/WebConfig.java
Labels: 개발 🧑‍💻, 백 🐯, 우선순위 ⭐⭐

#251 Fix: GetTeamCalendarStatus (#250)
  src/main/java/promisor/promisor/domain/bandate/service/BanDateService.java
Labels: 개발 🧑‍💻, 리팩터링 🔧, 우선순위 ⭐⭐⭐, 백 🐯

#258 Refactor: ModifymodifyMemberInfoAPI(#257)
  src/main/java/promisor/promisor/domain/member/dto/ModifyMemberDto.java
  src/main/java/promisor/promisor/domain/member/service/MemberService.java
Labels: 개발 🧑‍💻, 리팩터링 🔧, 우선순위 ⭐⭐⭐, 백 🐯

#265 Feat: Connect Promise API (#211)
  client/src/pages/Promise.tsx
  client/src/pages/PromiseDetail.tsx
  client/src/pages/PromiseLocation.tsx
Labels: 개발 🧑‍💻, 프론트 🐰

#266 Feat: Connect Promise Detail API (#211)
  client/src/pages/PromiseDate.tsx
Labels: 개발 🧑‍💻, 프론트 🐰

#272 Refactor: AddValidationOfPostingReason(#271)
  src/main/java/promisor/promisor/domain/bandate/api/BanDateController.java
  src/main/java/promisor/promisor/domain/bandate/dto/RegisterReasonDto.java
  src/main/java/promisor/promisor/domain/bandate/service/BanDateService.java
Labels: 개발 🧑‍💻, 리팩터링 🔧, 우선순위 ⭐⭐⭐

#273 Feat: Add edit promise API (#223)
  src/main/java/promisor/promisor/domain/bandate/dao/PersonalBanDateRepository.java
  src/main/java/promisor/promisor/domain/promise/api/PromiseController.java
  src/main/java/promisor/promisor/domain/promise/dao/PromiseRepository.java
  src/main/java/promisor/promisor/domain/promise/domain/Promise.java
  src/main/java/promisor/promisor/domain/promise/dto/PromiseResponse.java
  src/main/java/promisor/promisor/domain/promise/service/PromiseService.java
Labels: 개발 🧑‍💻, 백 🐯, 우선순위 ⭐⭐

#274 Feat: Add CORS origins for map API
  src/main/java/promisor/promisor/global/config/WebConfig.java
Labels: 개발 🧑‍💻

#276 Refactor: getGroups (#275)
  src/main/java/promisor/promisor/domain/team/dto/SearchGroupResponse.java
  src/main/java/promisor/promisor/domain/team/service/TeamService.java
Labels: 개발 🧑‍💻, 리팩터링 🔧, 우선순위 ⭐⭐⭐, 백 🐯

#277 Feat: Connect MyPage Calander (#225)
  client/src/organisms/MyPageModal.tsx
  client/src/pages/MyPage.tsx
Labels: 개발 🧑‍💻, 프론트 🐰

#280 Refactor: tuning jpql query (#279)
  src/main/java/promisor/promisor/domain/team/api/TeamController.java
  src/main/java/promisor/promisor/domain/team/dao/TeamRepository.java
  src/main/java/promisor/promisor/domain/team/domain/Team.java
  src/main/java/promisor/promisor/domain/team/domain/TeamMember.java
  src/main/java/promisor/promisor/domain/team/dto/GetMidPointResponse.java
  src/main/java/promisor/promisor/domain/team/dto/SearchGroupResponse.java
  src/main/java/promisor/promisor/domain/team/service/TeamService.java
Labels: 개발 🧑‍💻, 리팩터링 🔧, 우선순위 ⭐⭐⭐, 백 🐯

#281 Refactor: Dto 요청, 응답 패키지로 분리
  src/main/java/promisor/promisor/domain/member/api/MemberController.java
  src/main/java/promisor/promisor/domain/member/api/RelationController.java
  src/main/java/promisor/promisor/domain/member/dto/request/FollowFriendRequest.java
  src/main/java/promisor/promisor/domain/member/dto/request/LoginRequest.java
  src/main/java/promisor/promisor/domain/member/dto/request/ModifyMemberRequest.java
  src/main/java/promisor/promisor/domain/member/dto/request/SignUpRequest.java
  src/main/java/promisor/promisor/domain/member/dto/response/FollowFriendResponse.java
  src/main/java/promisor/promisor/domain/member/dto/response/LoginResponse.java
  src/main/java/promisor/promisor/domain/member/dto/response/MemberResponse.java
  src/main/java/promisor/promisor/domain/member/dto/response/ModifyMemberResponse.java
  src/main/java/promisor/promisor/domain/member/dto/response/ProfileMemberResponse.java
  src/main/java/promisor/promisor/domain/member/dto/response/TokenResponse.java
  src/main/java/promisor/promisor/domain/member/service/MemberService.java
  src/main/java/promisor/promisor/domain/member/service/RelationService.java
  src/main/java/promisor/promisor/domain/promise/api/PromiseController.java
  src/main/java/promisor/promisor/domain/promise/dto/request/PromiseCreateRequest.java
  src/main/java/promisor/promisor/domain/promise/dto/request/PromiseDateEditRequest.java
  src/main/java/promisor/promisor/domain/promise/dto/response/PromiseResponse.java
  src/main/java/promisor/promisor/domain/promise/service/PromiseService.java
  src/main/java/promisor/promisor/domain/team/api/TeamController.java
  src/main/java/promisor/promisor/domain/team/dao/TeamMemberRepository.java
  src/main/java/promisor/promisor/domain/team/domain/TeamMember.java
  src/main/java/promisor/promisor/domain/team/dto/DelegateLeaderDto.java
  src/main/java/promisor/promisor/domain/team/dto/EditMyLocationDto.java
  src/main/java/promisor/promisor/domain/team/dto/EditMyLocationResponse.java
  src/main/java/promisor/promisor/domain/team/dto/GroupMemberDto.java
  src/main/java/promisor/promisor/domain/team/dto/InviteTeamDto.java
  src/main/java/promisor/promisor/domain/team/dto/request/CreateTeamRequest.java
  src/main/java/promisor/promisor/domain/team/dto/request/DelegateLeaderRequest.java
  src/main/java/promisor/promisor/domain/team/dto/request/EditMyLocationRequest.java
  src/main/java/promisor/promisor/domain/team/dto/request/EditTeamRequest.java
  src/main/java/promisor/promisor/domain/team/dto/request/InviteTeamRequest.java
  src/main/java/promisor/promisor/domain/team/dto/response/ChangeTeamNameResponse.java
  src/main/java/promisor/promisor/domain/team/dto/response/DelegateLeaderResponse.java
  src/main/java/promisor/promisor/domain/team/dto/response/EditMyLocationResponse.java
  src/main/java/promisor/promisor/domain/team/dto/response/GetMidPointResponse.java
  src/main/java/promisor/promisor/domain/team/dto/response/GetMyTeamResponse.java
  src/main/java/promisor/promisor/domain/team/dto/response/GetTeamMembersLocationResponse.java
  src/main/java/promisor/promisor/domain/team/dto/response/InviteTeamResponse.java
  src/main/java/promisor/promisor/domain/team/dto/response/LeaveTeamResponse.java
  src/main/java/promisor/promisor/domain/team/dto/response/SearchGroupResponse.java
  src/main/java/promisor/promisor/domain/team/service/TeamService.java
  src/main/java/promisor/promisor/global/config/ResponseMap.java
  src/main/java/promisor/promisor/global/config/security/CustomAuthenticationFilter.java
Labels: 개발 🧑‍💻, 리팩터링 🔧, 우선순위 ⭐, 백 🐯

#283 Fix/remove duplicate query keys
  client/public/index.html
  client/src/organisms/PlaceList.tsx
  client/src/organisms/PromiseDateCalendar.tsx
  client/src/organisms/PromiseDateModal.tsx
  client/src/organisms/PromiseLocationMap.tsx
  client/src/pages/Group.tsx
  client/src/pages/Promise.tsx
  client/src/pages/PromiseDate.tsx
  client/src/pages/PromiseDetail.tsx
  client/src/pages/PromiseLocation.tsx
  client/src/utils/dateFormatter.ts
  client/src/utils/kakaoMap.ts
  yarn.lock
Labels: 버그 🪲, 프론트 🐰

#285 Fix/duplicate key error
  client/src/organisms/AddModal.tsx
  client/src/template/BasedTemplate.tsx
Labels: 버그 🪲, 프론트 🐰

#287 Fix/automatically delete refresh token
  client/src/auth/api.ts
  client/src/auth/refresh.ts
Labels: 버그 🪲, 프론트 🐰

#288 Fix: Change event에서 리렌더링 오류 수정 (#233)
  client/src/atoms/Btn.tsx
  client/src/organisms/AddModal.tsx
  client/src/pages/Promise.tsx
Labels: 버그 🪲, 프론트 🐰

#290 Feat/separate promise detail page
  client/src/App.tsx
  client/src/auth/api.ts
  client/src/auth/config.ts
  client/src/auth/refresh.ts
  client/src/image/marker.png
  client/src/index.tsx
  client/src/organisms/PlaceList.tsx
  client/src/organisms/PromiseDateCalendar.tsx
  client/src/organisms/PromiseDateModal.tsx
  client/src/organisms/PromiseDetailNav.tsx
  client/src/organisms/PromiseDetailTitle.tsx
  client/src/organisms/PromiseLocationMap.tsx
  client/src/organisms/RoundElement.tsx
  client/src/pages/Group.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/PromiseDate.tsx
  client/src/pages/PromiseDetail.tsx
  client/src/pages/PromiseLocation.tsx
  client/src/pages/PromisePlace.tsx
  client/src/pages/_index.ts
Labels: 리팩터링 🔧, 프론트 🐰

#292 Fix: 그룹원 초대 체크박스 오류 해결 (#291)
  client/src/App.tsx
  client/src/Theme.ts
  client/src/organisms/FriendList.tsx
  client/src/organisms/PromiseDetailNav.tsx
  client/src/organisms/RoundElement.tsx
  client/src/pages/Group.tsx
  client/src/pages/GroupMaker.tsx
  client/src/pages/Promise.tsx
Labels: 버그 🪲, 프론트 🐰

#294 Feat: 약속 장소 직접 입력 (#293)
  client/src/organisms/PlaceList.tsx
  client/src/pages/PromisePlace.tsx
Labels: 개발 🧑‍💻, 프론트 🐰

#295 Refactor: 메서드 분리를 통한 가독성 개선
  src/main/java/promisor/promisor/global/auth/AuthorizationExtractor.java
Labels: 리팩터링 🔧, 백 🐯

#296 Style: 컨벤션 일부 수정
  src/main/java/promisor/promisor/domain/bandate/api/BanDateController.java
  src/main/java/promisor/promisor/domain/member/api/RelationController.java
  src/main/java/promisor/promisor/domain/member/dao/MemberRepository.java
  src/main/java/promisor/promisor/domain/team/service/TeamService.java
  src/main/java/promisor/promisor/global/auth/JwtAuthArgumentResolver.java
  src/main/java/promisor/promisor/global/auth/JwtService.java
  src/main/java/promisor/promisor/global/error/CustomAuthenticationEntryPoint.java
Labels: 리팩터링 🔧, 백 🐯

#298 Refactor: 연관관계에 따라 dependency 분리 (#297)
  build.gradle
  src/main/java/promisor/promisor/domain/team/domain/TeamMember.java
  src/main/java/promisor/promisor/domain/team/service/TeamService.java
  src/main/java/promisor/promisor/global/auth/AuthorizationExtractor.java
  src/main/java/promisor/promisor/global/config/WebSecurityConfig.java
Labels: 리팩터링 🔧, 백 🐯, 우선순위 ⭐⭐
